### ISSUE TITLE
"First model: a single hidden layer" ->   raise TypeError("cost must be a scalar.")

### ISSUE THREAD

**Issue by antgr** [dnouri/kfkd-tutorial#12]
Hello, I copy paste the trace. Thanx
Antonis

mouth_center_bottom_lip_y    7016
Image                        7049
dtype: int64
  InputLayer        	(None, 9216)        	produces    9216 outputs
  DenseLayer        	(None, 100)         	produces     100 outputs
  DenseLayer        	(None, 30)          	produces      30 outputs
Traceback (most recent call last):
  File "kfkd.py", line 82, in <module>
    net1.fit(X, y)
  File "/home/antonis/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nolearn/lasagne.py", line 241, in fit
    self.initialize()
  File "/home/antonis/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nolearn/lasagne.py", line 155, in initialize
    self.y_tensor_type,
  File "/home/antonis/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/nolearn/lasagne.py", line 207, in _create_iter_funcs
    updates = update(loss_train, all_params, **update_params)
  File "/home/antonis/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/updates.py", line 40, in nesterov_momentum
    all_grads = theano.grad(loss, all_params)
  File "/home/antonis/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/theano/gradient.py", line 427, in grad
    raise TypeError("cost must be a scalar.")
TypeError: cost must be a scalar.

**Comment by dnouri** [comment]
How did you install Lasagne and Theano?

**Comment by antgr** [comment]
With pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt
I tried the mnist.py example and worked ok. Examles were at /media/antonis/4d787ed5-a34f-4af8-b66b-9d4bf93312b4/home/ant/new_Lasagne/src/lasagne/examples (all that yesterday night). 
Today I could not find the above folder.
I tried again the example mnist.py and there was an error: AttributeError: 'module' object has no attribute 'categorical_crossentropy'. So I downloaded Lasagne-master in my home folder and I installed it from source, python setup.py install.

**Comment by dnouri** [comment]
You need to use exactly the versions listed in the two requirements files:
```
git+https://github.com/Theano/Theano.git@b84464261ffa1d451097ac5e5243dcd8f7e0ff62#egg=Theano
git+https://github.com/benanne/Lasagne.git@490f45de4d1e9f77969a729588f6971744f423e9#egg=Lasagne
git+https://github.com/dnouri/nolearn.git@5ac73106947dbb4cc692cb15e3ea4d22e46b173c#egg=nolearn
-e git+https://github.com/lisa-lab/pylearn2.git@2f4537665c9f036c32c80b0c967b49ebb0b5f9ce#egg=pylearn2
```
Newer versions of Lasagne and nolearn are slightly incompatible with the current version of the tutorial.

**Comment by antgr** [comment]
Thanks
