### ISSUE TITLE
does not work with latest version of libraries

### ISSUE THREAD

**Issue by kylemcdonald** [dnouri/kfkd-tutorial#13]
after setting up a virtualenv with all the requirements satisfied and seeing that this example runs correctly, i was curious if i could also run it with the latest version of theano, lasagne, and nolearn but i ran into a problem:

```
kfkd-tutorial kyle$ python kfkd.py fit
Using gpu device 0: GeForce GT 750M
left_eye_center_x            7039
left_eye_center_y            7039
right_eye_center_x           7036
right_eye_center_y           7036
left_eye_inner_corner_x      2271
left_eye_inner_corner_y      2271
left_eye_outer_corner_x      2267
left_eye_outer_corner_y      2267
right_eye_inner_corner_x     2268
right_eye_inner_corner_y     2268
right_eye_outer_corner_x     2268
right_eye_outer_corner_y     2268
left_eyebrow_inner_end_x     2270
left_eyebrow_inner_end_y     2270
left_eyebrow_outer_end_x     2225
left_eyebrow_outer_end_y     2225
right_eyebrow_inner_end_x    2270
right_eyebrow_inner_end_y    2270
right_eyebrow_outer_end_x    2236
right_eyebrow_outer_end_y    2236
nose_tip_x                   7049
nose_tip_y                   7049
mouth_left_corner_x          2269
mouth_left_corner_y          2269
mouth_right_corner_x         2270
mouth_right_corner_y         2270
mouth_center_top_lip_x       2275
mouth_center_top_lip_y       2275
mouth_center_bottom_lip_x    7016
mouth_center_bottom_lip_y    7016
Image                        7049
dtype: int64
/usr/local/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/layers/helper.py:52: UserWarning: get_all_layers() has been changed to return layers in topological order. The former implementation is still available as get_all_layers_old(), but will be removed before the first release of Lasagne. To ignore this warning, use `warnings.filterwarnings('ignore', '.*topo.*')`.
  warnings.warn("get_all_layers() has been changed to return layers in "
  DenseLayer        	(None, 30)          	produces      30 outputs
  DenseLayer        	(None, 1000)        	produces    1000 outputs
  DropoutLayer      	(None, 1000)        	produces    1000 outputs
  DenseLayer        	(None, 1000)        	produces    1000 outputs
  DropoutLayer      	(None, 128, 11, 11) 	produces   15488 outputs
  MaxPool2DCCLayer  	(None, 128, 11, 11) 	produces   15488 outputs
  Conv2DCCLayer     	(None, 128, 22, 22) 	produces   61952 outputs
  DropoutLayer      	(None, 64, 23, 23)  	produces   33856 outputs
  MaxPool2DCCLayer  	(None, 64, 23, 23)  	produces   33856 outputs
  Conv2DCCLayer     	(None, 64, 46, 46)  	produces  135424 outputs
  DropoutLayer      	(None, 32, 47, 47)  	produces   70688 outputs
  MaxPool2DCCLayer  	(None, 32, 47, 47)  	produces   70688 outputs
  Conv2DCCLayer     	(None, 32, 94, 94)  	produces  282752 outputs
  InputLayer        	(None, 1, 96, 96)   	produces    9216 outputs
Traceback (most recent call last):
  File "kfkd.py", line 417, in <module>
    func(*sys.argv[2:])
  File "kfkd.py", line 222, in fit
    net.fit(X, y)
  File "/usr/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 145, in fit
    self.y_tensor_type,
  File "/usr/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 295, in _create_iter_funcs
    updates = update(loss_train, all_params, **update_params)
  File "/usr/local/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg/lasagne/updates.py", line 40, in nesterov_momentum
    all_grads = theano.grad(loss, all_params)
  File "/usr/local/lib/python2.7/site-packages/theano/gradient.py", line 432, in grad
    raise TypeError("cost must be a scalar.")
TypeError: cost must be a scalar.
```

here is a little more info about what versions i mean by 'latest' -- Theano and nolearn from pip, Lasagne straight from github:

```
$ pip show Theano lasagne nolearn
---
Name: Theano
Version: 0.7.0
Location: /usr/local/lib/python2.7/site-packages
Requires: numpy, scipy
---
Name: Lasagne
Version: 0.1.dev0
Location: /usr/local/lib/python2.7/site-packages/Lasagne-0.1dev-py2.7.egg
Requires: numpy, Theano
---
Name: nolearn
Version: 0.5
Location: /usr/local/lib/python2.7/site-packages
Requires: docopt, gdbn, joblib, scikit-learn
```

**Comment by kylemcdonald** [comment]
this seems to be a nolearn problem, i'll post the bug there instead.

**Comment by kylemcdonald** [comment]
i have a new bug, but it looks like this one was just because i was using a new version of lasagne but not the correspondingly new version of nolearn. sorry for the distraction!
