### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by dylansun** [dnouri/kfkd-tutorial#19]
Hi, when I set up the environment I run `python kfkd.py fit`
I got an error, however I'm not quite familiar with python. I can solve it by myself. Here is what it outputs:
```
Using gpu device 0: GeForce GTX TITAN Black
left_eye_center_x            7039
left_eye_center_y            7039
right_eye_center_x           7036
right_eye_center_y           7036
left_eye_inner_corner_x      2271
left_eye_inner_corner_y      2271
left_eye_outer_corner_x      2267
left_eye_outer_corner_y      2267
right_eye_inner_corner_x     2268
right_eye_inner_corner_y     2268
right_eye_outer_corner_x     2268
right_eye_outer_corner_y     2268
left_eyebrow_inner_end_x     2270
left_eyebrow_inner_end_y     2270
left_eyebrow_outer_end_x     2225
left_eyebrow_outer_end_y     2225
right_eyebrow_inner_end_x    2270
right_eyebrow_inner_end_y    2270
right_eyebrow_outer_end_x    2236
right_eyebrow_outer_end_y    2236
nose_tip_x                   7049
nose_tip_y                   7049
mouth_left_corner_x          2269
mouth_left_corner_y          2269
mouth_right_corner_x         2270
mouth_right_corner_y         2270
mouth_center_top_lip_x       2275
mouth_center_top_lip_y       2275
mouth_center_bottom_lip_x    7016
mouth_center_bottom_lip_y    7016
Image                        7049
dtype: int64
Traceback (most recent call last):
  File "kfkd.py", line 410, in <module>
    func(*sys.argv[2:])
  File "kfkd.py", line 215, in fit
    net.fit(X, y)
  File "/home/sll/LAS_ENV/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 263, in fit
    self.initialize()
  File "/home/sll/LAS_ENV/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 155, in initialize
    out = self._output_layer = self.initialize_layers()
  File "/home/sll/LAS_ENV/local/lib/python2.7/site-packages/nolearn/lasagne.py", line 199, in initialize_layers
    layer = layer_factory(layer, name=layer_name, **layer_params)
TypeError: __init__() takes at least 3 arguments (2 given)
```

**Comment by dnouri** [comment]
If you update nolearn to the latest from Git, it should give you a more helpful error message.  The problem here is that Lasagne changed some of its parameters, e.g. MaxPool2DLayer's `ds` parameter has been renamed to `pool_size`.  I've updated the tutorial online to reflect this change.

**Comment by dylansun** [comment]
After I upgrade the nolearn, it works.
