### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by shivang27** [dnouri/kfkd-tutorial#20]
Getting the following error while trying to train the neural net.
MemoryError: you might consider using 'theano.shared(..., borrow=True)'

Full Traceback :
Traceback (most recent call last):
  File "C:/Users/Shivang/PycharmProjects/firstprogram/cnn.py", line 60, in <module>
    net1.fit(X, y)
  File "C:\Python27\lib\site-packages\nolearn\lasagne\base.py", line 290, in fit
    self.initialize()
  File "C:\Python27\lib\site-packages\nolearn\lasagne\base.py", line 149, in initialize
    out = self._output_layer = self.initialize_layers()
  File "C:\Python27\lib\site-packages\nolearn\lasagne\base.py", line 221, in initialize_layers
    layer = layer_factory(**layer_kw)
  File "c:\python27\scripts\src\lasagne\lasagne\layers\dense.py", line 66, in __init__
    self.W = self.create_param(W, (num_inputs, num_units), name="W")
  File "c:\python27\scripts\src\lasagne\lasagne\layers\base.py", line 240, in create_param
    return theano.shared(utils.floatX(arr), name=name)
  File "C:\Python27\lib\site-packages\theano\compile\sharedvalue.py", line 208, in shared
    allow_downcast=allow_downcast, **kwargs)
  File "C:\Python27\lib\site-packages\theano\tensor\sharedvar.py", line 44, in tensor_constructor
    value=numpy.array(value, copy=(not borrow)),
MemoryError: you might consider using 'theano.shared(..., borrow=True)'
 Please help
Thanks in advance 
Regards
Shivang

**Comment by dnouri** [comment]
It looks like your GPU may not have enough RAM.  Maybe try to reduce your network's size to fewer weights.
