### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by eduardmelnychenko** [dnouri/kfkd-tutorial#26]
Hello, 

After starting '/src/lasagne/examples$ python mnist.py' I've got the following error:

eduard@eduard-MS-7851:~/src/lasagne/examples$ python mnist.py
Loading data...
Downloading MNIST dataset
Traceback (most recent call last):
  File "mnist.py", line 239, in <module>
    main()
  File "mnist.py", line 208, in main
    dataset = load_data()
  File "mnist.py", line 53, in load_data
    data = _load_data()
  File "mnist.py", line 45, in _load_data
    urlretrieve(url, filename)
  File "/home/eduard/anaconda/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/eduard/anaconda/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 13] Permission denied: 'mnist.pkl.gz'

Regards,

Eduard

**Comment by dnouri** [comment]
Looks like you don't have write permissions in that directory.
