### ISSUE TITLE
crash with GPU

### ISSUE THREAD

**Issue by mungzh** [dnouri/kfkd-tutorial#29]
I used the Theano test code to check if Theano installed correctly. Without using gpu, the test code worked out well. Then I installed cuda toolkit, set up the environment variables for it, and build a .theanorc file to indicate using gpu. That's where I got the error. It says,

Traceback (most recent call last):
  File "theanotest.py", line 4, in <module>
    from theano import function, config, shared, sandbox
  File "/home/anaconda2/lib/python2.7/site-packages/theano/**init**.py", line 103, in <module>
    import theano.sandbox.cuda
  File "/home/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/**init**.py", line 694, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)
  File "/home/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/**init**.py", line 573, in use
    cnmem = min(config.lib.cnmem, 0.98) \* 100
TypeError: function takes at most 1 argument (2 given)

How could I fix this issue?

**Comment by JunjieHu** [comment]
I have exactly the same problem! Look for a solution.

**Comment by mungzh** [comment]
I fixed it by uninstalling Theano. It turned out that I had two different versions installed. The issue is probably caused by mixed Theano versions. Now I'm only using Theano 0.7.0.
