### ISSUE TITLE
mnist.py fails on startup

### ISSUE THREAD

**Issue by BrianWestlake** [dnouri/kfkd-tutorial#32]
Running using Cuda 8.0 RC and a GTX 1080 I get the following result using the standard install instructions:

andrew@andrew-Ubuntu:~$ cd src/lasagne/examples/
andrew@andrew-Ubuntu:~/src/lasagne/examples$ python mnist.py
Using gpu device 0: GeForce GTX 1080
Loading data...
Building model and compiling functions...
Traceback (most recent call last):
  File "mnist.py", line 239, in <module>
    main()
  File "mnist.py", line 215, in main
    iter_funcs = create_iter_functions(dataset, output_layer)
  File "mnist.py", line 126, in create_iter_functions
    objective = lasagne.objectives.Objective(output_layer,
AttributeError: 'module' object has no attribute 'Objective'

**Comment by dnouri** [comment]
I've updated the requirements, can you run this again:

`pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt`
