### ISSUE TITLE
Cannot import theano

### ISSUE THREAD

**Issue by jiaoshuo** [dnouri/kfkd-tutorial#9]
I used 

sudo pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt
sudo pip install -r https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements-2.txt

 to install the Prerequisites on Mac yosemite. But when I tried to import theano, I got the following error

>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/theano/__init__.py", line 44, in <module>
    from theano.gof import \
  File "/Library/Python/2.7/site-packages/theano/gof/__init__.py", line 38, in <module>
    from theano.gof.cc import \
  File "/Library/Python/2.7/site-packages/theano/gof/cc.py", line 63, in <module>
    from theano.gof import link
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 12, in <module>
    from theano.gof.type import Type
  File "/Library/Python/2.7/site-packages/theano/gof/type.py", line 14, in <module>
    from theano.gof.op import CLinkerObject
  File "/Library/Python/2.7/site-packages/theano/gof/op.py", line 29, in <module>
    from theano.gof.cmodule import GCC_compiler
  File "/Library/Python/2.7/site-packages/theano/gof/cmodule.py", line 37, in <module>
    from theano.gof.compiledir import gcc_version_str, local_bitwidth
  File "/Library/Python/2.7/site-packages/theano/gof/compiledir.py", line 250, in <module>
    in_c_key=False)
  File "/Library/Python/2.7/site-packages/theano/configparser.py", line 243, in AddConfigVar
    configparam.__get__()
  File "/Library/Python/2.7/site-packages/theano/configparser.py", line 285, in __get__
    self.__set__(None, val_str)
  File "/Library/Python/2.7/site-packages/theano/configparser.py", line 296, in __set__
    self.val = self.filter(val)
  File "/Library/Python/2.7/site-packages/theano/gof/compiledir.py", line 185, in filter_compiledir
    " or listing permissions." % path)
ValueError: compiledir '/Users/shuo/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64' exists but you don't have read, write or listing permissions.

**Comment by dnouri** [comment]
On 02/10/2015 05:24 AM, jiaoshuo wrote:
> I used
> 
> sudo pip install -r
> https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements.txt
> sudo pip install -r
> https://raw.githubusercontent.com/dnouri/kfkd-tutorial/master/requirements-2.txt
> 
> to install the Prerequisites on Mac yosemite. But when I tried to import
> theano, I got the following error
> 
>             import theano
>             Traceback (most recent call last):
>             ...
>             ValueError: compiledir
>             '/Users/shuo/.theano/compiledir_Darwin-14.1.0-x86_64-i386-64bit-i386-2.7.6-64'
>             exists but you don't have read, write or listing permissions.

Looks like you have a filesystem permissions problem!  Try and remove
that '/Users/shuo/.theano/' directory and run Python again without sudo.

**Comment by jiaoshuo** [comment]
It works now! Thanks.
